### ISSUE TITLE
Required that I define "#elif" ?

### ISSUE THREAD

**Issue by pa-0** [Winterreisender/EzPptTimer#1]
Hi, new to C++, but I was under the impression that custom if / else-if statements require defining the "elif" as a custom macro so that it is compiled correctly? Am I mistaken on that?

Thanks.

**Comment by Winterreisender** [comment]
Sorry, but your behavior seems not understandable for me. Could you explain yourself more clearly?

**Comment by pa-0** [comment]
Sure. In the source code for EzSlideTimer (shown below), you have an `#if`/ `#else-if` statement, where `#else if` is abbreviated like so: **`#elif`**
```cpp
#elif defined(__APPLE__) //<---here
    // GL 3.2 + GLSL 150
    const char *glsl_version = "#version 150";
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE); // 3.2+ only
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);     
```
It is my understanding that **the shorthand `#elif` does not exist in C++**[^1] as a substitute for `#else if` as it does in other languages (such as `python`, for example).

### My question is this:
Does
#### `#elif`
need to be revised to
#### `#else if`
for the code to properly compile?

[^1]: [Source (https://runestone.academy/ns/books/published/cpp4python/Control_Structures/conditionals.html#elif)](https://runestone.academy/ns/books/published/cpp4python/Control_Structures/conditionals.html#elif)

**Comment by Winterreisender** [comment]
I got it.
"#elif" may be not a standard c or c++ grammar but it does be supported by many compilers, such as msvc:
https://learn.microsoft.com/en-us/cpp/preprocessor/hash-if-hash-elif-hash-else-and-hash-endif-directives-c-cpp?view=msvc-170
Also note that "elif" and "#elif" are totally different grammar.

**Comment by pa-0** [comment]
Thank you for explaining that! IT is much appreciated.
